import os

SYMBOL = os.getenv('BINANCE_SYMBOL', 'BTCUSDT')
GRID_LEVELS = 10
PRICE_RANGE_PCT = 5
ORDER_AMOUNT = 10
CHECK_INTERVAL = 10

PAPER_MODE = True
PAPER_BALANCE = 100

API_KEY = os.getenv('BINANCE_API_KEY', '')
API_SECRET = os.getenv('BINANCE_API_SECRET', '')